name: Flutter iOS Release Build

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
#         flutter-version: '2.10.4'
        channel: 'stable'
        architecture: x64
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v3
      with:
        name: 'ios-release-build.app'
        path: '/Users/runner/work/flutter_example/flutter_example/build/ios/iphoneos/Runner.app'
