name: Flutter Android Release APK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
#         flutter-version: '2.10.4'
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release
    - uses: actions/upload-artifact@v1
      with:
        name: android-release-apk-build
#         path: '/Users/runner/work/flutter_example/flutter_example/build/ios/iphoneos/Runner.app'
