name: Flutter Android Debug Build

on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
#         flutter-version: '2.10.4'
        channel: 'stable'
    - run: javac -version
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug
    - uses: actions/upload-artifact@v3
      with:
        name: android-debug-apk
        path: 'build/app/outputs/flutter-apk/app-debug.apk'
    - run: flutter build appbundle --debug
    - uses: actions/upload-artifact@v3
      with:
        name: android-debug-appbundle
        path: 'build/app/outputs/bundle/debug/app-debug.aab'
